/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.dataperpuscontroller;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.SwingConstants;
/**
 *
 * @author Lab Informatika
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    
    dataperpuscontroller dc;
    
    public MainView() {
        initComponents();
        dc= new dataperpuscontroller(this);
        dc.isitabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDataperpus = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JTextnama = new javax.swing.JTextField();
        JTextpenulis = new javax.swing.JTextField();
        JTextrating = new javax.swing.JTextField();
        JTexthasil = new javax.swing.JTextField();
        jButtontambah = new javax.swing.JButton();
        jButtonubah = new javax.swing.JButton();
        jButtonhapus = new javax.swing.JButton();
        jButtonreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Sistem Management Perpustakaan");

        tabelDataperpus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "judul", "Penulis", "Rating", "Harga"
            }
        ));
        tabelDataperpus.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelDataperpusAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tabelDataperpusAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(tabelDataperpus);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Judul Buku");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Penulis");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rating");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Harga Pinjam");

        JTextnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTextnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextnamaActionPerformed(evt);
            }
        });

        JTextpenulis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTextpenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextpenulisActionPerformed(evt);
            }
        });

        JTextrating.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTextrating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextratingActionPerformed(evt);
            }
        });

        JTexthasil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JTexthasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTexthasilActionPerformed(evt);
            }
        });

        jButtontambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtontambah.setText("Tambah");
        jButtontambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontambahActionPerformed(evt);
            }
        });

        jButtonubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonubah.setText("Ubah");
        jButtonubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonubahActionPerformed(evt);
            }
        });

        jButtonhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonhapus.setText("Hapus");
        jButtonhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonhapusActionPerformed(evt);
            }
        });

        jButtonreset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonreset.setText("Reset");
        jButtonreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(JTextrating, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(JTextnama, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTextpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(JTexthasil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButtontambah)
                        .addGap(84, 84, 84)
                        .addComponent(jButtonubah)
                        .addGap(88, 88, 88)
                        .addComponent(jButtonhapus)
                        .addGap(57, 57, 57)
                        .addComponent(jButtonreset)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextpenulis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTextrating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTexthasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtontambah)
                    .addComponent(jButtonubah)
                    .addComponent(jButtonhapus)
                    .addComponent(jButtonreset))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTextnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextnamaActionPerformed

    private void JTextpenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextpenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextpenulisActionPerformed

    private void JTextratingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextratingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTextratingActionPerformed

    private void JTexthasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTexthasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTexthasilActionPerformed

    private void jButtontambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontambahActionPerformed
        dc.insert();
        dc.isitabel();
    }//GEN-LAST:event_jButtontambahActionPerformed

    private void jButtonubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonubahActionPerformed
        dc.update();
        dc.isitabel();
    }//GEN-LAST:event_jButtonubahActionPerformed

    private void jButtonhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonhapusActionPerformed
        dc.delete();
        dc.isitabel();
    }//GEN-LAST:event_jButtonhapusActionPerformed

    private void jButtonresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonresetActionPerformed
        dc.reset();
    }//GEN-LAST:event_jButtonresetActionPerformed

    private void tabelDataperpusMouseClicked(java.awt.event.MouseEvent evt) {                                            
        // TODO add your handling code here:
        
        int baris = tabelDataperpus.getSelectedRow();
        JTextnama.setText(tabelDataperpus.getValueAt(baris, 0).toString());
        JTextpenulis.setText(tabelDataperpus.getValueAt(baris, 1).toString());
        JTextrating.setText(tabelDataperpus.getValueAt(baris, 2).toString());
        JTexthasil.setText(tabelDataperpus.getValueAt(baris, 3).toString());

    }     
    private void tabelDataperpusAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelDataperpusAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelDataperpusAncestorAdded

    private void tabelDataperpusAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelDataperpusAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelDataperpusAncestorMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTexthasil;
    private javax.swing.JTextField JTextnama;
    private javax.swing.JTextField JTextpenulis;
    private javax.swing.JTextField JTextrating;
    private javax.swing.JButton jButtonhapus;
    private javax.swing.JButton jButtonreset;
    private javax.swing.JButton jButtontambah;
    private javax.swing.JButton jButtonubah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelDataperpus;
    // End of variables declaration//GEN-END:variables
    public JTable getTabelDataperpus() {
        return tabelDataperpus;
    }

    public void setTabelDataperpus(JTable tabelDataperpus) {
        this.tabelDataperpus = tabelDataperpus;
    }

    public JTextField getJTextrating() {
        return JTextrating;
    }

    public void setJTextrating(JTextField JTextrating) {
        this.JTextrating = JTextrating;
    }

    public JTextField getJTextpenulis() {
        return JTextpenulis;
    }

    public void setJTextpenulis(JTextField JTextpenulis) {
        this.JTextpenulis = JTextpenulis;
    }

    public JTextField getJTextnama() {
        return JTextnama;
    }

    public void setJTextnama(JTextField JTextnama) {
        this.JTextnama = JTextnama;
    }

    public JTextField getJTexthasil() {
        return JTexthasil;
    }

    public void setJTexthasil(JTextField JTexthasil) {
        this.JTexthasil = JTexthasil;
    }

    public Object getJTxtpenulis() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getJTxtrating() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getJTxtharga() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getJTxtnama() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public Object getJTxthasil() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

}
